# This file has been generated by node2nix 1.4.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "imap-0.8.19" = {
      name = "imap";
      packageName = "imap";
      version = "0.8.19";
      src = fetchurl {
        url = "https://registry.npmjs.org/imap/-/imap-0.8.19.tgz";
        sha1 = "3678873934ab09cea6ba48741f284da2af59d8d5";
      };
    };
    "optimist-0.6.1" = {
      name = "optimist";
      packageName = "optimist";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/optimist/-/optimist-0.6.1.tgz";
        sha1 = "da3ea74686fa21a19a111c326e90eb15a0196686";
      };
    };
    "printf-0.2.5" = {
      name = "printf";
      packageName = "printf";
      version = "0.2.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/printf/-/printf-0.2.5.tgz";
        sha1 = "c438ca2ca33e3927671db4ab69c0e52f936a4f0f";
      };
    };
    "winston-0.8.3" = {
      name = "winston";
      packageName = "winston";
      version = "0.8.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/winston/-/winston-0.8.3.tgz";
        sha1 = "64b6abf4cd01adcaefd5009393b1d8e8bec19db0";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "xenvar-0.5.1" = {
      name = "xenvar";
      packageName = "xenvar";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xenvar/-/xenvar-0.5.1.tgz";
        sha1 = "f82d2fedee63af76687b70115ce6274dc71310e9";
      };
    };
    "bunyan-1.8.12" = {
      name = "bunyan";
      packageName = "bunyan";
      version = "1.8.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/bunyan/-/bunyan-1.8.12.tgz";
        sha1 = "f150f0f6748abdd72aeae84f04403be2ef113797";
      };
    };
    "utf7-1.0.2" = {
      name = "utf7";
      packageName = "utf7";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/utf7/-/utf7-1.0.2.tgz";
        sha1 = "955f490aae653ba220b9456a0a8776c199360991";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "semver-5.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.3.0.tgz";
        sha1 = "9b2ce5d3de02d17c6012ad326aa6b4d0cf54f94f";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "wordwrap-0.0.3" = {
      name = "wordwrap";
      packageName = "wordwrap";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/wordwrap/-/wordwrap-0.0.3.tgz";
        sha1 = "a3d5da6cd5c0bc0008d37234bbaf1bed63059107";
      };
    };
    "minimist-0.0.10" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.10.tgz";
        sha1 = "de3f98543dbf96082be48ad1a0c7cda836301dcf";
      };
    };
    "async-0.2.10" = {
      name = "async";
      packageName = "async";
      version = "0.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-0.2.10.tgz";
        sha1 = "b6bbe0b0674b9d719708ca38de8c237cb526c3d1";
      };
    };
    "colors-0.6.2" = {
      name = "colors";
      packageName = "colors";
      version = "0.6.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/colors/-/colors-0.6.2.tgz";
        sha1 = "2423fe6678ac0c5dae8852e5d0e5be08c997abcc";
      };
    };
    "cycle-1.0.3" = {
      name = "cycle";
      packageName = "cycle";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/cycle/-/cycle-1.0.3.tgz";
        sha1 = "21e80b2be8580f98b468f379430662b046c34ad2";
      };
    };
    "eyes-0.1.8" = {
      name = "eyes";
      packageName = "eyes";
      version = "0.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/eyes/-/eyes-0.1.8.tgz";
        sha1 = "62cf120234c683785d902348a800ef3e0cc20bc0";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "pkginfo-0.3.1" = {
      name = "pkginfo";
      packageName = "pkginfo";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pkginfo/-/pkginfo-0.3.1.tgz";
        sha1 = "5b29f6a81f70717142e09e765bbeab97b4f81e21";
      };
    };
    "stack-trace-0.0.10" = {
      name = "stack-trace";
      packageName = "stack-trace";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/stack-trace/-/stack-trace-0.0.10.tgz";
        sha1 = "547c70b347e8d32b4e108ea1a2a159e5fdde19c0";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "dtrace-provider-0.8.5" = {
      name = "dtrace-provider";
      packageName = "dtrace-provider";
      version = "0.8.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/dtrace-provider/-/dtrace-provider-0.8.5.tgz";
        sha1 = "98ebba221afac46e1c39fd36858d8f9367524b92";
      };
    };
    "mv-2.1.1" = {
      name = "mv";
      packageName = "mv";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mv/-/mv-2.1.1.tgz";
        sha1 = "ae6ce0d6f6d5e0a4f7d893798d03c1ea9559b6a2";
      };
    };
    "safe-json-stringify-1.0.4" = {
      name = "safe-json-stringify";
      packageName = "safe-json-stringify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/safe-json-stringify/-/safe-json-stringify-1.0.4.tgz";
        sha1 = "81a098f447e4bbc3ff3312a243521bc060ef5911";
      };
    };
    "moment-2.19.4" = {
      name = "moment";
      packageName = "moment";
      version = "2.19.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/moment/-/moment-2.19.4.tgz";
        sha512 = "14wvy144672p4zgqjw2g3iljmhqdgf0db4blbjbakq9dvb6n3n22qx6s21w96i9kc9i0nr09kwq55cw3csiqc9jxhwgfbfj941564fp";
      };
    };
    "nan-2.8.0" = {
      name = "nan";
      packageName = "nan";
      version = "2.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/nan/-/nan-2.8.0.tgz";
        sha1 = "ed715f3fe9de02b57a5e6252d90a96675e1f085a";
      };
    };
    "ncp-2.0.0" = {
      name = "ncp";
      packageName = "ncp";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ncp/-/ncp-2.0.0.tgz";
        sha1 = "195a21d6c46e361d2fb1281ba38b91e9df7bdbb3";
      };
    };
    "rimraf-2.4.5" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.4.5.tgz";
        sha1 = "ee710ce5d93a8fdb856fb5ea8ff0e2d75934b2da";
      };
    };
    "glob-6.0.4" = {
      name = "glob";
      packageName = "glob";
      version = "6.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-6.0.4.tgz";
        sha1 = "0f08860f6a155127b2fadd4f9ce24b1aab6e4d22";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "1879a3j85h92ypvb7lpv1dqpcxl49rqnbgs5la18zmj1yqhwl60c2m74254wbr5pp3znckqpkg9dvjyrz6hfz8b9vag5a3j910db4f8";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.8" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.8.tgz";
        sha1 = "c07b211c7c952ec1f8efd51a77ef0d1d3990a292";
      };
    };
    "balanced-match-1.0.0" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.0.tgz";
        sha1 = "89b4d199ab2bee49de164ea02b89ce462d71b767";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
  };
in
{
  imapnotify = nodeEnv.buildNodePackage {
    name = "imapnotify";
    packageName = "imapnotify";
    version = "0.4.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/imapnotify/-/imapnotify-0.4.1.tgz";
      sha512 = "0fn58ydrck0mwpq48pj2in6aql522avzyabrddq4ixykr1h29ha3cvh1v0mga8ghg1v9zpkii81qqac74qwm9ikr1kll616fcz0cc0s";
    };
    dependencies = [
      (sources."imap-0.8.19" // {
        dependencies = [
          (sources."utf7-1.0.2" // {
            dependencies = [
              sources."semver-5.3.0"
            ];
          })
          (sources."readable-stream-1.1.14" // {
            dependencies = [
              sources."core-util-is-1.0.2"
              sources."isarray-0.0.1"
              sources."string_decoder-0.10.31"
              sources."inherits-2.0.3"
            ];
          })
        ];
      })
      (sources."optimist-0.6.1" // {
        dependencies = [
          sources."wordwrap-0.0.3"
          sources."minimist-0.0.10"
        ];
      })
      sources."printf-0.2.5"
      (sources."winston-0.8.3" // {
        dependencies = [
          sources."async-0.2.10"
          sources."colors-0.6.2"
          sources."cycle-1.0.3"
          sources."eyes-0.1.8"
          sources."isstream-0.1.2"
          sources."pkginfo-0.3.1"
          sources."stack-trace-0.0.10"
        ];
      })
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      sources."xenvar-0.5.1"
      (sources."bunyan-1.8.12" // {
        dependencies = [
          (sources."dtrace-provider-0.8.5" // {
            dependencies = [
              sources."nan-2.8.0"
            ];
          })
          (sources."mv-2.1.1" // {
            dependencies = [
              sources."ncp-2.0.0"
              (sources."rimraf-2.4.5" // {
                dependencies = [
                  (sources."glob-6.0.4" // {
                    dependencies = [
                      (sources."inflight-1.0.6" // {
                        dependencies = [
                          sources."wrappy-1.0.2"
                        ];
                      })
                      sources."inherits-2.0.3"
                      (sources."minimatch-3.0.4" // {
                        dependencies = [
                          (sources."brace-expansion-1.1.8" // {
                            dependencies = [
                              sources."balanced-match-1.0.0"
                              sources."concat-map-0.0.1"
                            ];
                          })
                        ];
                      })
                      (sources."once-1.4.0" // {
                        dependencies = [
                          sources."wrappy-1.0.2"
                        ];
                      })
                      sources."path-is-absolute-1.0.1"
                    ];
                  })
                ];
              })
            ];
          })
          sources."safe-json-stringify-1.0.4"
          sources."moment-2.19.4"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Execute scripts on new messages using IDLE imap command";
      homepage = "https://github.com/a-sk/node-imapnotify#readme";
      license = "MIT";
    };
    production = true;
  };
}